steps:
  # Step 1: Build Docker image from Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - us-central1-docker.pkg.dev/$PROJECT_ID/ash-docker-repo/hello-docker:$SHORT_SHA
      - 'CLOUDBUILD-DOCKER-APP'

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/ash-docker-repo/hello-docker:$SHORT_SHA

# Optional: list the image in the build results
#images:
 # - us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/hello-docker:$SHORT_SHA
